apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: angeldominguez97/spring-petclinic-config-server-test:3.2.4
        ports:
        - containerPort: 8888
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        livenessProbe:
          httpGet:
            path: /
            port: 8888
          initialDelaySeconds: 6
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: angeldominguez97/spring-petclinic-discovery-server-test:3.2.4
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 6
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: angeldominguez97/spring-petclinic-admin-server-test:3.2.4
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 6
          periodSeconds: 10
-
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        image: angeldominguez97/spring-petclinic-customers-test:3.2.4
        ports:
        - containerPort: 8081
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 6
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: angeldominguez97/spring-petclinic-visits-test:3.2.4
        ports:
        - containerPort: 8082
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 6
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: angeldominguez97/spring-petclinic-vets-test:3.2.4
        ports:
        - containerPort: 8083
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 6
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana-server
        image: grafana/grafana
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus-server
        image: prom/prometheus
        ports:
        - containerPort: 9090
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: angeldominguez97/spring-petclinic-api-gateway-test:3.2.4
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        - name: ZIPKIN_BASE_URL
          value: "http://tracing-server:9411"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 6
          periodSeconds: 10