apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: davidunir945/spring-petclinic-admin-server-test
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        resources:
          limits:
            memory: "512Mi"
