apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: angeldominguez97/spring-petclinic-config-server-test:3.2.4
          ports:
            - containerPort: 8888
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5

