apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: angeldominguez97/spring-petclinic-customers-test:3.2.4
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
          