apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana-server
        image: grafana/grafana
        ports:
        - containerPort: 3000
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"        
        resources:
          limits:
            memory: "256Mi"

