apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
        - name: tracing-server
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411