apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: davidunir945/spring-petclinic-visits-test
        ports:
        - containerPort: 8082
        env:
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"        
        resources:
          limits:
            memory: "512Mi"

